// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

/// <reference types="@cloudflare/workers-types" />

interface CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
}
